### ISSUE TITLE
Add upstream rpm-packaging support into Delorean

### ISSUE THREAD

**Issue by hguemar** [openstack-packages/DLRN#13]
Summary: RDO use a per-project repository setup while upstream packaging use per-project directories in a **single** git repository.

Delorean should be able to support that setup so that we could setup a delorean instance for gating and testing. This is a pre-requisite for upstream packaging group.

**Comment by hguemar** [comment]
cc  @apevec @derekhiggins @yac @javierpena

**Comment by javierpena** [comment]
Looking at the dlrn code, I see 3 main areas where this would require changes:

- Package information retrieval (getpackages function) should not be tied to rdoinfo, but pluggable. An additional plugin that clones the upstream rpm-packaging repo and populates the packages structure with one package per directory under openstack/ would be required.

- Git repo handling functions (refreshrepo / getinfo) should also be pluggable, so we have one plugin per repo schema (per-project repos, or single repo)

- Finally, renderspec should be used to get a usable spec file.

**Comment by apevec** [comment]
> Package information retrieval (getpackages function) should not be tied to rdoinfo

ack - also to support non-OpenStack projects like ODL

**Comment by dfarrell07** [comment]
> also to support non-OpenStack projects like ODL

/me is here from ODL upstream packaging world, FYI

+1 to being able to use DLRN for ODL upstream.

**Comment by javierpena** [comment]
https://review.rdoproject.org/r/1084 is a first step in making package info retrieval pluggable. If this is seen as a viable alternative, we can move forward and use a similar idea for git repo handling.

**Comment by javierpena** [comment]
More WIP work with https://review.rdoproject.org/r/1100 .

**Comment by apevec** [comment]
@javierpena this is done and running as 3rd party CI in openstack/rpm-packaging right?

**Comment by javierpena** [comment]
Right, closing.
