### ISSUE TITLE
Can not install delorean on CentOS

### ISSUE THREAD

**Issue by sshnaidm** [openstack-packages/DLRN#16]
Delorean comes with setuptools>17 and CentOS doesn't have it in repos, so it fails to install. The problem that setuptools requirements is in test-requirements.txt, and not in requirements.txt, but is still required for installation. So anybody who install it with "pip install -r requirements.txt" will fail.
Reproduce:
just run "pip install delorean" on CentOS

**Comment by dmsimard** [comment]
So, I think requirements need to be fixed at large. Setuptools does need to be moved to requirements.txt but so does Mock and so on.
Good catch.

**Comment by javierpena** [comment]
Actually, I've had the same issue, and even adding setuptools>17 to requirements.txt didn't work for me. I had to pre-install it, see https://github.com/rdo-infra/puppet-dlrn/blob/master/manifests/worker.pp#L164-L171 for details on how it worked for me.

An up-to-date tox manages to work for the installation, but I think it does because it updates setuptools as part of its setup.

**Comment by javierpena** [comment]
Actually, after some more tests all we need to do is to upgrade pip before trying to install DLRN. "pip install -U pip", then "pip install -r requirements.txt" works fine for me.

**Comment by dmsimard** [comment]
@javierpena it's probably fair to move mock to requirements.txt, it's an actual requirement (and not one using only in tests or build) and since setuptools is required for mock, move it as well

**Comment by javierpena** [comment]
@dmsimard yes, but even then, since the CentOS-distributed version of virtualenv bundles pip 1.4, pip install will fail due to the different setuptools version. We need an updated pip for this.

**Comment by javierpena** [comment]
Also, we have two different "mocks" here. One is the mock command, used to build packages, which is needed at runtime. The other one is the mock python library, which afaik is only required when running tests. @dmsimard  is this correct?

**Comment by dmsimard** [comment]
That's right, I always confuse the two mocks. I don't know, actually. You're probably right that it's only used for tests.
