### ISSUE TITLE
Cover edge case when package is renamed in rdoinfo

### ISSUE THREAD

**Issue by javierpena** [openstack-packages/DLRN#18]
Renaming a package in rdoinfo can lead to a repo issue, since the following chain of events could happen:

- we have oldpkg_name built with commit X and distgit commit Y
- when renaming the package, as soon as rdoinfo is updated, DLRN finds a newpkg_name and builds it
- newpkg_name will be build with the same commit X and distgit commit Y, overwriting the old ones with new packages, using the same hash but a different timestamp
- if there are any repos with symlinks to the old rpm name, those links will be broken and a package install would fail

I'm not sure how DLRN could cover this, some ideas:

- maybe offline tool which checks for dangling symlinks ? (apevec)
- just detect this by checking if there is a commit from another project with the same commit and distgit hash, then abort if that happens?

**Comment by apevec** [comment]
Example where this happened:
https://trunk.rdoproject.org/centos7-mitaka/82/ef/82ef95501d3a3fa08dda5b491e59e86db1e6c120_b796987d was first build 2016-06-01 21:44:43
with openstack-tripleo-common-2.0.1-0.20160601214508.82ef955.el7.centos.noarch.rpm:

Then rdoinfo change https://review.rdoproject.org/r/#/c/1291/ was merged and DLRN picked it up on 2016-06-03 14:16:28 and since there wasn't changes to either upstream or distgit, it has recreated 82ef95501d3a3fa08dda5b491e59e86db1e6c120_b796987d with openstack-tripleo-common-2.0.1-0.20160603141715.82ef955.el7.centos.noarch.rpm
Same RPM content just with a different timestamp in NVR !

**Comment by apevec** [comment]
> detect this by checking if there is a commit from another project with the same commit and distgit hash

:+1:  for checkig if there's a _successfull_ commit+distgit.  DLRN should stop by default if it detects there's existing hashed_repo with a successful build, only failed builds can be overwritten.

**Comment by hguemar** [comment]
Another way would be detecting if the spec file has been renamed in the last commit, then create a new snapshot with a different hash.

**Comment by javierpena** [comment]
@hguemar in that case there was no rename to the spec file, just the project name changed (that's a DB thing).

**Comment by javierpena** [comment]
I think the patch for this could be a one-liner.

If we remove this line: https://github.com/openstack-packages/DLRN/blob/master/dlrn/shell.py#L232, we are checking if the commit we want to process is not already there, regardless of the project_name. 

Currently we are filtering by project_name, which makes sense in general but creates this corner case. The only case where this would fail is if we have a hash collision in *both* the commit_hash and distro_hash on two unrelated projects, but anyway this would create issues with the current code, wouldn't it?

**Comment by apevec** [comment]
commit_hash+distro_hash must be unique with the current setup, so proposed fix is part of it but it would silently skip edge cases, while we might want to alerts when they happen?

**Comment by hguemar** [comment]
@javierpena spec was renamed => https://review.rdoproject.org/r/#/c/1139/

**Comment by javierpena** [comment]
@apevec after some thinking, I'd say it's better not to alert. Failing would cause a review to be opened (where nothing can be done), we wouldn't have a consistent repo, and all we'd have to do is just wait for a new commit to happen on the repo.

@hguemar actually, what caused the issue was https://review.rdoproject.org/r/#/dashboard/self . Renaming the spec file should be ok.

**Comment by apevec** [comment]
:+1: for after thinking, good point about automated FTBFS reviews
