### ISSUE TITLE
DLRN doesn't exit 1 if build errors occur

### ISSUE THREAD

**Issue by dprince** [openstack-packages/DLRN#20]
In TripleO CI we've just noticed that DLRN build errors don't fail our CI jobs. Specifically we see this log message getting printed 'packages not built correctly: not updating the consistent symlink'... and those jobs can go on to pass TripleO CI giving us potentially false positive results.

**Comment by javierpena** [comment]
Looking at the code, we set exit_code=1 as soon as there is one build error (https://github.com/openstack-packages/DLRN/blob/master/dlrn/shell.py#L318), and use that code to return at the end (https://github.com/openstack-packages/DLRN/blob/master/dlrn/shell.py#L406).

The log message you mention is expected when not every package is built, it is just letting us know that the "consistent" symlink is not being created (as some packages are not done), can you post the link to one the failed CI jobs?

**Comment by javierpena** [comment]
I think this was confirmed to be a different issue, + https://review.rdoproject.org/r/1737 added the option to return 2 when some packages were set to RETRY state. Closing.
