### ISSUE TITLE
It'd be nice to "stream" the output of rpmbuild.log as dlrn builds the package

### ISSUE THREAD

**Issue by dmsimard** [openstack-packages/DLRN#21]
When dlrn builds a package there is ~10 minutes where no output is given while it's building the package. It'd be great to see that output, even with an additional command line argument or something.

**Comment by javierpena** [comment]
The rpmbuild.log output can be checked with tail at the hashed repo directory during build. Do you mean you'd like to see that as part of the dlrn output? Why?

**Comment by dmsimard** [comment]
@javierpena when looking at a jenkins console log, for example.

**Comment by javierpena** [comment]
http://review.rdoproject.org/r/1828 should fix this.
