### ISSUE TITLE
rsync can fail to atomically upload files

### ISSUE THREAD

**Issue by dmsimard** [openstack-packages/DLRN#23]
We just got a situation with

    centos-master/aa/7b/aa7b87c8d3abef0016c871cfdbfb1bdd5c492f03_35361f65

This repository was symlinked on the passive instance for current and consistent but did not actually exist. Everything completed successfully on the internal dlrn instance, however, in the dlrn-logs, we can see that the rsync failed:

    WARNING:dlrn:Failed to sync directory /home/centos-master/data/repos/./aa/7b/aa7b87c8d3abef0016c871cfdbfb1bdd5c492f03_35361f65 to centos-master@54.81.116.189:/home/centos-master/data/repos ,got error 
    
      RAN: '/usr/bin/rsync -avzR --delete -e ssh -p 3300 -o StrictHostKeyChecking=no /home/centos-master/data/repos/./aa/7b/aa7b87c8d3abef0016c871cfdbfb1bdd5c492f03_35361f65 centos-master@54.81.116.189:/home/centos-master/data/repos'
    
      STDOUT:
    
    
      STDERR:
    ssh: connect to host 54.81.116.189 port 3300: Connection timed out
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
    
    WARNING:dlrn:Failed to sync directory /home/centos-master/data/repos/./status_report.html to centos-master@54.81.116.189:/home/centos-master/data/repos ,got error 
    
      RAN: '/usr/bin/rsync -avzR --delete -e ssh -p 3300 -o StrictHostKeyChecking=no /home/centos-master/data/repos/./status_report.html centos-master@54.81.116.189:/home/centos-master/data/repos'
    
      STDOUT:
    
    
      STDERR:
    ssh: connect to host 54.81.116.189 port 3300: Connection timed out
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]

**Comment by apevec** [comment]
yeah, it's currently multiple rsync commands https://github.com/openstack-packages/DLRN/blob/master/dlrn/shell.py#L741

**Comment by javierpena** [comment]
https://review.rdoproject.org/r/1772 aims at fixing this.
