### ISSUE TITLE
dlrn should zuul-clone rdoinfo if it's in-gate (run_tests.sh)

### ISSUE THREAD

**Issue by dmsimard** [openstack-packages/DLRN#24]
Right now we're passing a rdoinfo git url to dlrn and letting it do a regular git clone.

If we would pre-provision rdoinfo (through zuul-cloner || git clone) and pass a path to rdoinfo to dlrn instead, we could use in-flight reviews of rdoinfo and test them with dlrn with Depends-On.

**Comment by javierpena** [comment]
We have two places where we could/should implement this change:

- When calling map-project-name (https://github.com/openstack-packages/DLRN/blob/master/scripts/run_tests.sh#L30). I think that would also require a change in the map-project-name script itself, as it always assumes a remote Git URL for rdoinfo.

- When calling dlrn itself (https://github.com/openstack-packages/DLRN/blob/master/scripts/run_tests.sh#L77), we can add --rdoinfo <local path> using a local rdoinfo repo already fetched by zuul-cloner.

I guess both are needed? The second item should be pretty straightforward.

**Comment by dmsimard** [comment]
Yeah.. we definitely need to touch map project name to avoid the "hardcoding" of a rdoinfo location.

It might just be me but I feel like "map_project_name" should be a method provided by rdoinfo.
pip install rdoinfo
import rdoinfo
rdoinfo.map_project_name('something')

It feels hacky to have this in dlrn instead... I can probably take care of that part.

and yes, I expected to use the --rdoinfo parameter to dlrn like we do on the dlrn servers.
