### ISSUE TITLE
Can we timestamp the logs ?

### ISSUE THREAD

**Issue by dmsimard** [openstack-packages/DLRN#25]
I was tailing logs and noticed the git fetch is really slow on the internal server (due to the NFS) but from looking at logs in general (unless doing a tail) you can't really tell how slow it is.

And for a run, there's more than 400 of them...
====
    # grep -c Getting dlrn-run.1470873001.log
    432
====

====
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-horizon-distgit.git to /home/centos-newton/data/puppet-horizon_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-horizon to /home/centos-newton/data/puppet-horizon (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-ironic-distgit.git to /home/centos-newton/data/puppet-ironic_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-ironic to /home/centos-newton/data/puppet-ironic (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-keystone-distgit.git to /home/centos-newton/data/puppet-keystone_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-keystone to /home/centos-newton/data/puppet-keystone (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-manila-distgit.git to /home/centos-newton/data/puppet-manila_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-manila to /home/centos-newton/data/puppet-manila (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-neutron-distgit.git to /home/centos-newton/data/puppet-neutron_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-neutron to /home/centos-newton/data/puppet-neutron (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-nova-distgit.git to /home/centos-newton/data/puppet-nova_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-nova to /home/centos-newton/data/puppet-nova (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-oslo-distgit.git to /home/centos-newton/data/puppet-oslo_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-oslo to /home/centos-newton/data/puppet-oslo (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-openstack_extras-distgit.git to /home/centos-newton/data/puppet-openstack_extras_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-openstack_extras to /home/centos-newton/data/puppet-openstack_extras (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-openstacklib-distgit.git to /home/centos-newton/data/puppet-openstacklib_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-openstacklib to /home/centos-newton/data/puppet-openstacklib (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-sahara-distgit.git to /home/centos-newton/data/puppet-sahara_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-sahara to /home/centos-newton/data/puppet-sahara (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-swift-distgit.git to /home/centos-newton/data/puppet-swift_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-swift to /home/centos-newton/data/puppet-swift (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-tempest-distgit.git to /home/centos-newton/data/puppet-tempest_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-tempest to /home/centos-newton/data/puppet-tempest (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-tripleo-distgit.git to /home/centos-newton/data/puppet-tripleo_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-tripleo to /home/centos-newton/data/puppet-tripleo (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-trove-distgit.git to /home/centos-newton/data/puppet-trove_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-trove to /home/centos-newton/data/puppet-trove (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-vswitch-distgit.git to /home/centos-newton/data/puppet-vswitch_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-vswitch to /home/centos-newton/data/puppet-vswitch (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-ceph-distgit.git to /home/centos-newton/data/puppet-ceph_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-ceph to /home/centos-newton/data/puppet-ceph (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-n1k-vsm-distgit.git to /home/centos-newton/data/puppet-n1k-vsm_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-n1k-vsm to /home/centos-newton/data/puppet-n1k-vsm (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-mistral-distgit.git to /home/centos-newton/data/puppet-mistral_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-mistral to /home/centos-newton/data/puppet-mistral (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-zaqar-distgit.git to /home/centos-newton/data/puppet-zaqar_distro (rpm-master)
    INFO:dlrn:Getting git://git.openstack.org/openstack/puppet-zaqar to /home/centos-newton/data/puppet-zaqar (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-apache-distgit.git to /home/centos-newton/data/puppet-apache_distro (rpm-master)
    INFO:dlrn:Getting git://github.com/puppetlabs/puppetlabs-apache to /home/centos-newton/data/puppet-apache (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-concat-distgit.git to /home/centos-newton/data/puppet-concat_distro (rpm-master)
    INFO:dlrn:Getting git://github.com/puppetlabs/puppetlabs-concat to /home/centos-newton/data/puppet-concat (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-firewall-distgit.git to /home/centos-newton/data/puppet-firewall_distro (rpm-master)
    INFO:dlrn:Getting git://github.com/puppetlabs/puppetlabs-firewall to /home/centos-newton/data/puppet-firewall (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-haproxy-distgit.git to /home/centos-newton/data/puppet-haproxy_distro (rpm-master)
    INFO:dlrn:Getting git://github.com/puppetlabs/puppetlabs-haproxy to /home/centos-newton/data/puppet-haproxy (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-corosync-distgit.git to /home/centos-newton/data/puppet-corosync_distro (rpm-master)
    INFO:dlrn:Getting git://github.com/puppetlabs/puppetlabs-corosync to /home/centos-newton/data/puppet-corosync (master)
    INFO:dlrn:Getting http://review.rdoproject.org/r/p/puppet/puppet-git-distgit.git to /home/centos-newton/data/puppet-git_distro (rpm-master)
====

**Comment by javierpena** [comment]
It makes perfect sense :). https://github.com/openstack-packages/DLRN/issues/25 should solve it.
