### ISSUE TITLE
Delorean doesn't handle changes to git locations

### ISSUE THREAD

**Issue by derekhiggins** [openstack-packages/DLRN#8]
Changes to the location of a git repository in rdoinfo isn't handled by delorean,

delorean needs to check the origin remote and reset it if it changes

e.g. a change like this one requires manual intervention
https://github.com/redhat-openstack/rdoinfo/commit/f9858c49d2dc43b16dc2e59f43ad32eb46994693

**Comment by javierpena** [comment]
Fixed by https://review.rdoproject.org/r/1433
